services:
  nest-server:
    container_name: nest-server
    build: .
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      redis-cache:
        condition: service_healthy
      redis-broker:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend_network

  redis-cache:
    image: redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  redis-broker:
    image: redis
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  postgres:
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - backend_network

volumes:
  postgres_data:
    driver: local

networks:
  backend_network:
    driver: bridge
